name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: mr-smithers-excellent/docker-build-push@v3
      name: Build & Push docker image
      with:
        image:  jhajjaarap/go-middleware
        tag: 0.7.7
        registry: docker.io 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
